// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function solve(input) {
  return List.fold_left((function (acc, number) {
                return acc + number | 0;
              }), 0, List.map(Caml_format.caml_int_of_string, List.map((function (prim) {
                        return prim.trim();
                      }), List.map((function (string) {
                            return string.replace("+", "");
                          }), $$Array.to_list(input.replace((/\n/g), ",").split(","))))));
}

exports.solve = solve;
/* No side effect */
