// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Jest = require("@glennsl/bs-jest/src/jest.js");
var Solution = require("../src/solution.bs.js");

describe("Day 1", (function () {
        Jest.test("Should handle example situations correctly", (function (param) {
                Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](Solution.solve("+1, -2, +3, +1")));
                Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](Solution.solve("+1, +1, +1")));
                Jest.Expect[/* toBe */2](0, Jest.Expect[/* expect */0](Solution.solve("+1, +1, -2")));
                return Jest.Expect[/* toBe */2](-6, Jest.Expect[/* expect */0](Solution.solve("-1, -2, -3")));
              }));
        return Jest.test("Should handle provided input correctly", (function (param) {
                      return Jest.Expect[/* toBe */2](574, Jest.Expect[/* expect */0](Solution.solve(Fs.readFileSync("__tests__/input.txt", "utf8"))));
                    }));
      }));

/*  Not a pure module */
